More magnetic sync for AStepper
cisco-sbg-ui/magna-react pull request #103
Opened 2023-01-18 19:17 UTC by rwharrisjr

Resolves #100 

Note that the colors won't exactly line up since there is usage of two different color token sets in the design. Spacing, fonts and margins are also not 100%, but have been adjusted for a hopefully safe compromise between not breaking existing usage and getting somewhat closer to magnetic design.

2023-01-18 19:20 UTC, sabrinamokerji commented on framework/components/AStepper/AStepper.scss
> +      .a-step__tilte {
It looks like this might be a typo for `title`?

2023-01-18 19:22 UTC, rwharrisjr commented on framework/components/AStepper/AStepper.scss
> +      .a-step__tilte {
Good eye! Forgot to git add after I had updated that.

2023-01-24 16:18 UTC, brennarvo requested changes

2023-01-24 16:18 UTC, brennarvo commented on framework/components/AStepper/AStep.js
> +    if (children.length === 1 || (children[1] && !children[1].props.children)) {
I'm not sure if this is being applied correctly; right now in the UI, if I render just one child of `AStep`, it still looks like this with the margin:

![Screenshot 2023-01-24 at 10 04 46 AM](https://user-images.githubusercontent.com/94568316/214345499-e88fdca4-95c1-4a27-9a8d-3750ad766901.png)

I'm assuming that the reasoning for the `margin: 0` is to remove that (orange) margin so that it looks something like this (I hardcoded a zero margin into this example):

![Screenshot 2023-01-24 at 10 05 28 AM](https://user-images.githubusercontent.com/94568316/214345617-e5454e49-167a-4e74-bea2-6825c9dc1757.png)

I think a better way of checking this is with the [React Top-Level API's `React.Children.count` method](https://reactjs.org/docs/react-api.html#reactchildrencount), e.g., `React.Children.count(children) === 1`

2023-01-24 16:18 UTC, brennarvo commented on framework/components/AStepper/AStepper.scss
> +        //  background: map-get($theme, "steps", "step-icon-border-color");
Remove uncommented style

2023-01-24 16:18 UTC, brennarvo commented on framework/components/AStepper/AStepper.scss
> +        // background-color: map-deep-get($theme, "steps", "step-line-color");
Remove uncommented style

2023-01-24 16:36 UTC, brennarvo approved these changes
lgtm

2023-01-24 16:56 UTC, rwharrisjr commented
@sabrinamokerji This PR also adds a prop on `AStep` called `setActiveStep` - this will allow for clicking on steps to jump around in the stepper, and give control to specific use cases as needed.

2023-01-24 17:11 UTC, merged