Reconcile phosphor icons
cisco-sbg-ui/magna-react pull request #141
Opened 2023-01-30 22:31 UTC by rwharrisjr

This is a pass at brining in icons and replacing what was previously provided by Atomic with the Phosphor https://phosphoricons.com/ icon set. 

Icon names not available in Phosphor that were previously available in Atomic will still fallback to the original Atomic icon.

Note that this is a breaking change, as icon names for `AIcon` now map directly to Phosphor names. Any usage of `iconSet="magna"` should be removed and the icon name converted to hyphenated rather than camel case.

2023-02-23 21:21 UTC, brennarvo commented on scripts/copyPhosphorIcons.mjs
> +const generatedListForPhosphor = Object.keys(iconNameMap).map((key) => {
This might be a use-case for `Object.entries`:

```js
const generatedListForPhosphor = Object.entries(iconNameMap).map(
  ([atomicKey, phosphorKey]) => phosphorKey || atomicKey
);
```

Also, looking at how `generatedListForPhosphor` is used, could this just be a `filter`? With `map`, it will also include atomic icon names that don't resolve to any phosphor name, which means the ```path.resolve(`${phosphorPath}/${key}.svg`)``` on line 36 will fail (albeit it is being caught — I'm just not sure if that was the intent).

2023-02-23 22:24 UTC, rwharrisjr commented on scripts/copyPhosphorIcons.mjs
> +const generatedListForPhosphor = Object.keys(iconNameMap).map((key) => {
The intent was for it to fail with a warning - it gives us a way to know at the script run time which icons are falling back to atomic. In the future we may check for icons that match up and replace if needed.

 Updated code to use suggested `Object.entries`

2023-02-23 22:45 UTC, brennarvo commented on framework/components/AIcon/AIcon.js
> +      iconSet,
Wen can remove this prop now

2023-02-24 17:31 UTC, brennarvo requested changes

2023-02-24 17:31 UTC, brennarvo commented on framework/components/AIcon/AIcon.js
> +        console.log(children);
If this isn't intentional, we can remove

2023-02-24 17:31 UTC, brennarvo commented on framework/components/AIcon/AIcon.js
> +        <svg {...iconProps} {...componentProps} style={style}>
Adding `style` here will override the one defined on the `componentProps` object, which is used for a custom `size` prop (see lines 58-60).

We can just add the `style.stroke` assignment to `componentProps.style.stroke` instead.

2023-02-24 17:31 UTC, brennarvo commented on scripts/copyPhosphorIcons.mjs
> +const phosphorPath = `${os.homedir()}/Downloads/phosphor-icons/SVGs/Regular`;
The way I interpreted the requirements in #84  was that we need to support both `fill` and `stroke`.

2023-02-24 19:14 UTC, brennarvo approved these changes
LGTM 👍 Next beta release, we'll want to make sure to mention how the icon names need to be converted to kebab-case.

2023-02-24 19:27 UTC, merged