Tooltip delay proposal
cisco-sbg-ui/magna-react pull request #256
Opened 2023-03-07 15:59 UTC by mvelkCisco

Delays showing/hiding the tooltip by default when toggling `open` prop. This can be breaking for apps that implement delays themselves (like I do in intelligence), but it would make everything more consistent. 

Also adds a tip by default.

Examples updated to show tooltip on hover which is a more common and recommended use case: https://magnetic.cisco.com/0a43ab5cd/p/727988-popover

Relates to #255.

2023-03-07 20:49 UTC, rwharrisjr requested changes

2023-03-07 20:49 UTC, rwharrisjr commented on framework/components/ATooltip/ATooltip.js
> +    }, [open, openWithDelay, closeWithDelay]);
The `useEffect` needs a cleanup in case the tooltip unmounts before the timeout triggers

```
  return () => {
        if (timeout.current) {
        clearTimeout(timeout.current);
        }
      };
```

2023-03-07 20:49 UTC, rwharrisjr commented on framework/components/ATooltip/ATooltip.mdx
> +          <AButton ref={buttonRef11}  onMouseEnter={() => setOpen11(true)} onMouseLeave={() => setOpen11(false)}>
Nice, that has always bugged me that they weren't on hover.

2023-03-08 07:57 UTC, mvelkCisco commented on framework/components/ATooltip/ATooltip.js
> +    }, [open, openWithDelay, closeWithDelay]);
Right, good catch.

2023-03-08 10:25 UTC, mvelkCisco commented on framework/components/AFieldBase/AFieldBase.js
> +  infoTooltipProps: PropTypes.shape(infoTooltipProps),
`instanceOf` renders nicely in docs but does not actually validate props correctly. This does not render nicely in docs but at least it works.

2023-03-08 10:26 UTC, mvelkCisco commented on framework/components/ATooltip/ATooltip.js
> +export const ATooltipPropTypes = {
Looks like docs build has issues accessing `ATooltip.propTypes`. Maybe it's stripped out due to production build. This is a workaround.

2023-03-08 21:01 UTC, brennarvo commented
This makes sense and is a nice enhancement. I'm just not sure how I feel about a `useEffect` that updates internal state based off props. React actually makes a note of this: https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes. We're essentially doing a double-render whenever `open` changes.

I think maybe we could extract this out into a hook. That way, it's also not a breaking change, and we can still have the `open` prop be the "source of truth" for when the tooltip is opened"

```js
const { isOpen, open, close } = useTooltipState({ delay: "400ms" });

return (
  <>
    <button onMouseEnter={open} onMouseLeave={close}>
      Open Tooltip
    </button>
    <ATooltip open={isOpen} />
  </>
)
```

2023-03-08 21:53 UTC, rwharrisjr commented
Using a pattern we have elsewhere, this solution removes the controlled+uncontrolled nature of the current proposal and moves logic to a hook. This also has the benefit of no direct state management for easier readability. https://github.com/cisco-sbg-ui/magna-react/pull/268.

Effectively the linked PR takes the function code from this PR, puts it in a hook, and leaves `ATooltip` as is.

2023-03-09 09:05 UTC, mvelkCisco commented
To be honest I wasn't super thrilled with this proposal either. But I didn't have a better idea at the time. Now I would rather continue with the direction and discussion in #268.

2023-03-09 09:05 UTC, closed without merging