listen for defaultTheme prop change
cisco-sbg-ui/magna-react pull request #280
Opened 2023-03-10 15:48 UTC by mvelkCisco

fixes #279 

I'm not sure about any other side effects in that `useIsomorphicLayoutEffect`. I would rather review with fresh eyes.

2023-03-13 12:45 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> -          window.matchMedia("(prefers-color-scheme: dark)").matches
I think this is supposed to be handled by `AAutoTheme` and I'm not even sure how this behaved.

2023-03-13 12:51 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> -      let initialTheme = "default";
This is super confusing because there's `useState("dusk")` but `let initialTheme = "default"`.
This flips the current theme to `default` in this effect, but only if `persist` is true. So with `persist` the default was `dusk`, without `persist` it was `default`. 

In the new implementation, I assume `default` should be the default regardless the `persist` flag.

2023-03-13 13:06 UTC, mvelkCisco commented on framework/components/AApp/AApp.js
> +  theme: PropTypes.oneOf(["default", "dusk"])
I was hoping I could import `SUPPORTED_THEMES` from `ATheme` here, but the SSR breaks down when I do. It just sees a sting `SUPPORTED_THEMES` in `oneOf`.

2023-03-13 13:14 UTC, MikkCZ requested changes

2023-03-13 13:14 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +    const getInitialClientTheme = useCallback(() => {
This is only called from `useEffect`, which is only triggered once. Could you inline it there?

2023-03-13 13:14 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +const SUPPORTED_THEMES = [DEFAULT_THEME, DUSK_THEME];
I would just do
```js
const SUPPORTED_THEMES = {
  DEFAULT: "default",
  DUSK: "dusk"
};
```

If you need to iterate over them somewhere, use `Object.values(SUPPORTED_THEMES)`.

2023-03-13 13:14 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> -          window.matchMedia("(prefers-color-scheme: dark)").matches
I guess this is supposed to automatically follow the system/browser settings.

2023-03-13 13:21 UTC, MikkCZ requested changes

2023-03-13 13:21 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +      }
Also I would probably structure this code the other way around to eagerly return the first value available, or proceed to other fallbacks in order
```js
if (persist && typeof localStorage !== "undefined" && isSupportedTheme(localStorage.getItem(LS_KEY))) {
   return localStorage.getItem(LS_KEY);
} else if (isSupportedTheme(theme)) {
   return theme;
} else if (...) {
   ...
} else {
   return DEFAULT_THEME;
}
```

2023-03-13 13:21 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +    }, [theme]);
Won't there be a race-condition for these two?

2023-03-13 13:36 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> -          window.matchMedia("(prefers-color-scheme: dark)").matches
There a different component called `AAutoTheme` which sets the theme based on the system settings.

2023-03-13 13:37 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +    const getInitialClientTheme = useCallback(() => {
Technically I could, but I separated it for better semantics.

2023-03-13 13:38 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +    const getInitialClientTheme = useCallback(() => {
Not sure if there is any semantic difference, if you actually never care about the reference of `getInitialClientTheme`.

2023-03-13 13:49 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +const SUPPORTED_THEMES = [DEFAULT_THEME, DUSK_THEME];
I mostly wanted to have a `DEFAULT_THEME` const, so I can use it in both `useState` and as a fallback determining the initial theme, so they are kept in sync. But now I see the meaning is a bit confusing when one of the themes is also called `default`. I'll introduce a separate const for the syncing purpose.

Converting this to object just makes these harder to use in like 5 places. I never need the object. It's just 2 consts, I would keep it as it is for convenient access.

2023-03-13 13:51 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +const SUPPORTED_THEMES = [DEFAULT_THEME, DUSK_THEME];
Well, the idea would be to actually have an enum, and an object is probably as close as we could get to it here.

2023-03-13 13:53 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +      }
Right, my bad. I'll reverse this.

2023-03-13 15:07 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +    }, [theme]);
Please add a comment to the body of `getInitialClientTheme`, that the preference from `theme` really matters also to prevent this race condition.

2023-03-13 15:10 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +    const getInitialClientTheme = useCallback(() => {
To me this is just much easier to read.

I see a 3 line `useEffect` without dependencies that calls one function => in my brain this function runs on mount. Very explicit. I also like to double confirm with a comment.

I see a large `useEffect` without dependencies that references 3 different things => in my brain this is potentially a mistake that needs analysing. And I hate doing that :)

And yes, I don't care about the the reference of `getInitialClientTheme`. I could just remove `useCallback`, but I kind of add it automatically to avoid instantiating a function over and over again. It's possible it's a bigger performance overhead this way, not sure. But again, it stops my brain from immediately screaming "Missing useCallback!".

2023-03-13 15:17 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +    }, [currentTheme, persist, theme]);
This is the second place where `persist` and `theme` insteract or have some priority over each other. What about processing them once as

```js
const themeLocalStorage  = useMemo(() => {
   if (!theme && persist) {
     return localStorage;
   } else {
     return undefined;
   }
}, [theme, persist]);
```

And then call `themeStorage?.getItem`/`themeStorage?.setItem` without the need to repeatadly check whether to do it, or not.

Or even

```js
const themeLocalStorage  = useMemo(() => {
   if (!theme && persist) {
     return {
       get: () => localStorage?.getItem(LS_KEY) ?? undefined; // or coalesce to null, to mimic getItem call when the value is not there
       set: (t) => localStorage?.setItem(LS_KEY, t);
     };
   } else {
     return {
       get: () => undefined; // or null, to mimic getItem call when the value is not there
       set: (t) => {};
     };
   }
}, [theme, persist]);
```

2023-03-13 15:30 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +    }, [currentTheme, persist, theme]);
Hm, good idea... I'll try to do something like this. I might need to sprinkle in `typeof localStorage !== "undefined"` here and there too. Docs were crashing with just optional chaining, not sure why. And maybe a more descriptive name would be nice.

2023-03-14 08:13 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> -          window.matchMedia("(prefers-color-scheme: dark)").matches
This morning I've realised that this was probably meant to provide the system theme detection by default and `AAutoTheme` then overrides this and adds controls to the detection. So I'll add it back here.

2023-03-14 09:42 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +    }, [currentTheme, persist, theme]);
Please see the latest version. I've abstracted the storage, but I've kept the decision weather to actually use it separate. Making the storage return `undefined` when `theme` is set seem too non-transparent to me. I do make the decision about using the storage in one place now though.

2023-03-14 09:44 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +    }, [theme]);
I've ended up making the state `undefined` and I don't change it in the `theme` syncing hook util it has been initialized.

2023-03-14 11:24 UTC, MikkCZ requested changes

2023-03-14 11:24 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
`LS_KEY` can be `private readonly` inside the class.

2023-03-14 11:35 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
That's only supported by typescript.

2023-03-14 11:36 UTC, MikkCZ reviewed
Consider this approved from my side. But I will leave the actual approval for @rwharrisjr  or @brennarvo .

2023-03-15 19:39 UTC, rwharrisjr requested changes

2023-03-15 19:39 UTC, rwharrisjr commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
This seems to set the key in local storage to `undefined`. Removing the that key/value from local storage then seems to cause issues.

The following seems to resolve that on my machine:

```
const LS_KEY = "persist-magna-react-theme";

class ThemeStorage {
  static isSupported() {
    return typeof localStorage !== "undefined";
  }

  static loadTheme() {
    return localStorage.getItem(LS_KEY);
  }

  static saveTheme(theme) {
    localStorage.setItem(LS_KEY, theme);
  }
}
```

2023-03-16 07:27 UTC, MikkCZ commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
Good catch. The problem is the functions are static, and also what gets to `this` inside of them. @mvelkCisco there should be no need to actually move `LS_KEY` outside of the class, but you should be able to use it as `ThemeStorage.LS_KEY` (instead of `this.LS_KEY`).

2023-03-16 08:26 UTC, mvelkCisco commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
Ups, I've missed that. 

In any case, `this.LS_KEY` works fine as long as `LS_KEY` is `static` too. And `LS_KEY` needs to be `static` anyway to be used as `ThemeStorage.LS_KEY`. Thinking about `this` in `static` class hurts my brain. `ThemeStorage.LS_KEY` is probably better anyway, so I'm going with that for now.

2023-03-16 14:25 UTC, rwharrisjr commented on framework/components/ATheme/ATheme.js
> +  LS_KEY = "persist-magna-react-theme";
@MikkCZ yep that fixed it

2023-03-16 18:18 UTC, rwharrisjr approved these changes

2023-03-16 18:20 UTC, merged