fix ASelect component styles
cisco-sbg-ui/magna-react pull request #286
Opened 2023-03-13 10:50 UTC by rrubas

2023-03-13 10:52 UTC, rrubas commented
<img width="468" alt="Screenshot 2023-03-13 at 11 45 31" src="https://user-images.githubusercontent.com/19386887/224680949-e2129311-90d7-473c-beb1-4caa65748b8b.png">
<img width="461" alt="Screenshot 2023-03-13 at 11 48 36" src="https://user-images.githubusercontent.com/19386887/224680984-36164f55-7ff6-4c4a-b963-e08ce4c24cc9.png">
<img width="673" alt="223291743-698feec7-edbe-41d4-ae42-bce2592b9942" src="https://user-images.githubusercontent.com/19386887/224681020-9efc3dde-3865-405e-aa93-661d1d6b6c94.png">

2023-03-13 15:41 UTC, rwharrisjr requested changes

2023-03-13 15:41 UTC, rwharrisjr commented on framework/components/ASelect/ASelect.mdx
> -        medium
This section has the header "Medium". I think this section can be removed and then rename the next one "Size Variants" rather than "[Many Dropdown Options](https://magna-react-ow1locj26.securex-preview.app/components/select#many-dropdown-options)"

2023-03-14 07:31 UTC, rrubas commented
I kept the original "Many Dropdown Options" section and added a new "Size Variants" section where the sizes can be seen more clearly 
<img width="1096" alt="Screenshot 2023-03-14 at 8 29 03" src="https://user-images.githubusercontent.com/19386887/224927330-d498c229-a068-4867-af11-98a9040c1e0d.png">

2023-03-14 14:27 UTC, rwharrisjr approved these changes

2023-03-14 14:28 UTC, merged