fix: disable pointer events
cisco-sbg-ui/magna-react pull request #408
Opened 2023-05-24 19:09 UTC by androche

**Resolves #406 Prevent button events when disabled.**

**Problem**
`pointer-events: auto` allows click actions on links
`pointer-events: none` will prevent `cursor: not-allowed` from displaying

**Solution** 
Put a wrapper on the button to display `cursor: not-allowed` while preventing click action in child.

**Before**
![alertTest](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/40bcfaf8-6704-4b5a-9492-f6a083c8ed62)

**After**
![afterAlertTest](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/78e8e8b0-1c30-4a74-9184-5fd4278abc82)

2023-05-25 14:25 UTC, rwharrisjr requested changes

2023-05-25 14:25 UTC, rwharrisjr commented on framework/components/AButton/AButton.js
> +    if (disabled) {
This adds more DOM, and I don't think we want to do that since it changes existing structure on pages.

2023-05-25 14:25 UTC, rwharrisjr commented on framework/components/AButton/AButton.scss
> +    pointer-events: none;
`pointer-events: none` is good, but not all variations get the attribute. Additionally nothing adds the `disabled` class in AButton it appears.

```js
() => {
  return (
    <div>
      <AButton data-testid="click-test-button" disabled component={() => <a href="https://www.cisco.com">Should not be able to click</a>} />
    </div>
  );
}
```

This scenario fails since <a> tags don't get the disabled attribute.

2023-05-25 14:25 UTC, rwharrisjr commented on framework/components/AButton/AButton.js
> +    if (disabled) {
I think it might be better to add `a-button--disabled` to the `className`, and then update the scss to use that everywhere there's a reference to "disabled".

2023-05-25 14:31 UTC, rwharrisjr commented on framework/components/AButton/AButton.scss
> +    pointer-events: none;
^ might also be a good example to add to the mdx

2023-05-25 14:46 UTC, androche commented on framework/components/AButton/AButton.js
> +    if (disabled) {
Yea I did that first, but trouble is `pointer events: none` and `cursor: not allowed` can't be in the same class to work.

2023-05-25 14:47 UTC, androche commented on framework/components/AButton/AButton.js
> +    if (disabled) {
https://www.quora.com/How-can-I-set-pointer-events-to-none-as-well-as-cursor-to-not-allowed-simultaneously-in-CSS

2023-05-25 15:03 UTC, androche commented
Follow up on offline chat  - We are going with removing the disabled cursor for magna buttons altogether to avoid the wrapper complications and potential risk.

2023-05-26 15:45 UTC, rwharrisjr approved these changes

2023-05-26 15:45 UTC, merged