feat: submenus
cisco-sbg-ui/magna-react pull request #418
Opened 2023-06-06 18:36 UTC by androche

Resolved #403 - This provides an option for `AMenus` to display a list of items which may include submenus.
     *I also expanded the width of the menus to be more like magnetic- they were unusually slim.

 To convert a list item into a submenu list item, `<AListItem />` will need these props:
 ```js
  <AListItem
    ref={ref} //Your list item ref
    subMenu //Boolean which will allow submenu styling and behavior
    subMenuOnClose={setOpenSubmenu} //A submenu state handler to provide out-of-box mouseover and event handling
  />
```

Once this is provided you may nest as many submenus as your heart desires.  Magentic prefers a limit of 2 cascading menus as described here: https://magnetic.cisco.com/0a43ab5cd/p/321929-dropdown/t/115595

**Typical structure**
 ```js
//Main dropdown
<AMenu>
  //Submenu list item
  <AListItem>
    Submenu item
    //Your nested submenu with more items
    <AMenu>
      <AListItem />
      <AListItem />
    </AMenu >
   </AListItem >
   <AListItem>  Not a submenu item</AListItem>
 </AMenu>
```

**Sample**
![Screenshot 2023-06-05 at 4 24 16 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/ff64cb4c-4966-435f-bdde-7f31ef9293eb)

**Caveats**
Usage of the current components was ideal to allow flexibility,  familiarity, and a lot less duplicate code.  However, there may be some cooccurrences to account for.  One is if users have `closeOnClick` enabled on the parent `AMenu`, they will have to prevent the closing of the main menu if submenus are open.  In the example below, this is how we avoid two nested submenus from going byebye once closeOnClick is triggered.  The parent `AMenu` knows nothing about its list items and submenu children which is purposeful to avoid complexity.
```js
  <AMenu
    anchorRef={buttonRef}
    open={open}
    placement="bottom-left"
    onClose={() => {
      //Allow default closing of main menu if submenus aren't open
      if(!openSubmenu && !openNestedSubmenu) {
        setOpen(false);
      }
    }}>
```

Now that we've prevented closeOnClick for submenu events.  Users will have to instead close the main `AMenu` in the `onClick` for the nested list item.

Example:
```js
    <AListItem
      onClick={() => {
         alert("I'm a nested submenu action. Please fire");
         setOpen(false);; <//The parent/main menu state handler that is used for AMenu's `onClose`.
       }}>
       A submenu item 
     </AListItem />
```

**Demo**
**![nestedMenu](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/116d5206-4183-483f-9ae7-1ca253a68cf3)**

**TODO**
- Tabs and arrow functionality are at only 50% and not very straightforward.  Will add follow up PR to add focus to nested submenus. 
- Will also try to add a couple test cases.

2023-06-07 15:30 UTC, rwharrisjr requested changes

2023-06-07 15:30 UTC, rwharrisjr commented on framework/components/AMenu/AMenu.mdx
> +  <AMenu
Could we split this out into a separate section? That example playground is getting really long

2023-06-07 15:44 UTC, rwharrisjr commented
In the example, when opening the submenu with the right arrow key, then using left to close it, the "Disabled Item" is highlighted. Disabled probably shouldn't be allowed to get to that state

2023-06-07 15:48 UTC, androche commented on framework/components/AMenu/AMenu.mdx
> +  <AMenu
Yes I was having trouble navigating myself. I can rename things then too.

2023-06-07 16:02 UTC, androche commented
> ![Screenshot 2023-06-07 at 10 30 39 AM](https://user-images.githubusercontent.com/23561587/244119164-2b063773-9418-4e42-8c74-1551dd74e74b.png)
> 
> Not sure if this is desired to move the submenu in to the left when it opens close to the right side of the screen, or have it work like tippy with a "flip" behavior to move it fully left of the parent menu

Yea that's an issue with tooltip as well where users have to define their own position.   In this case, if someone were putting it over to the right, they could position the menu to open to the left.  

Ex: 
![Screenshot 2023-06-07 at 11 53 05 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/5dbb2981-ae7f-4c22-8102-fe56161a38ef)

2023-06-07 16:46 UTC, androche commented
> 

Just FYI looks disabled currently gets this applied.  Could add in skipping focus on disabled as part of the other follow up ticket?

![Screenshot 2023-06-07 at 12 42 05 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/f874356d-35b6-4622-ba5a-63a4263a5736)

2023-06-07 18:18 UTC, rwharrisjr commented
What if `subMenuOnClose` was moved to state inside the a component. It looks to be pretty tedious for the dev to implement a sub menu open state manually. The recursive logic could possible have a ASubMenuListItem component that uses `useToggle`

2023-06-07 20:59 UTC, androche commented
Yea 100% agree, dont love that either.  The main issue was the automatic close in the parent which tracking externally helped prevent here:
```
   <AMenu
    onClose={() => {
      //Allow default closing of main menu if submenus aren't open
      if (!openSubmenu) {
        setOpen2(false);
      }
    }}>
 ```
I have another idea i'll try out though that seems promising.

2023-06-13 18:17 UTC, rwharrisjr approved these changes

2023-06-13 18:28 UTC, merged