feat: Add AMultiSelect component
cisco-sbg-ui/magna-react pull request #419
Opened 2023-06-06 21:42 UTC by rwharrisjr

Currently only supports tags. Resolves #404 

![Screenshot 2023-06-06 at 4 41 45 PM](https://github.com/cisco-sbg-ui/magna-react/assets/23561587/a4d551f3-821d-413a-a53b-22e200d1bddc)

2023-06-07 16:54 UTC, androche reviewed
Works nicely!   Writing this as a comment because it doesn't have to be a blocker as i'm guilty of this myself in the other ticket, but the tabbing/arrows has some unwanted behavior.  I'll just post a couple gifs, but if you play around with it you can identify them:

Here I selected milk and cheese item, but it selected break and pasta item instead
![oddTab-Arrows](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/3be9258d-6589-4c92-840b-7dc1a01101ae)

Arrows/tabs skipping "Fruit".  (The beginning holdup is me trying to focus in on the form - had some trouble with that.)
![tabSkipping](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/62a7f3ee-821f-44c7-9979-7f8e951aff2d)

It's somehow possible to do both arrow and tabs at the same time - and they have different styles:
![twoSelections](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/b5d42304-fb7b-498a-8cf2-e2f76bac0bb9)

On blur toggle seems to be the same either way.
![validationBlurSame](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/248f41d1-4c47-4cd5-9917-04ba149ecb4b)

2023-06-07 18:09 UTC, rwharrisjr commented
@androche keyboard handling issues should be resolved now. Root cause was https://github.com/cisco-sbg-ui/magna-react/blob/canary/framework/components/AMenu/AMenu.js#L73-L75, when using DOMRect for placement - which is needed since the anchorRef can change size based on selection - it was set to ignore keyboard handling more menu items

2023-06-14 18:53 UTC, androche requested changes
Looks really good - notes below

2023-06-14 18:53 UTC, androche commented on framework/components/AMultiSelect/AMultiSelect.js
> +          //e.target.value.toLowerCase()
can remove

2023-06-14 18:53 UTC, androche commented on framework/components/AMultiSelect/AMultiSelect.js
> +            {filteredItems.map((item, index) => {
It might be nice to break all these logic blocks out to clean up the component a bit as its pretty hefty.

2023-06-14 18:53 UTC, androche commented on framework/components/AMultiSelect/AMultiSelect.scss
> +
Before fixing this, can you take a look at https://github.com/cisco-sbg-ui/magna-react/pull/439 🙏 😃 

![width](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/082f373d-df4d-411f-966a-7b05da69d733)

2023-06-15 21:34 UTC, androche commented on framework/components/AMultiSelect/AMultiSelect.scss
> +.a-multiselect {
`a-field-base` is set to a width of 100% so if there was a scenario where it was wrapped in a container with a flex-grow or a greater width it stretches with it.
![Screenshot 2023-06-15 at 5 28 17 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/355b8f4a-2b37-421f-b0ee-5c6f3d030c8d)


Looks like if you do a `width:unset` here it will help avoid this stretch and doesn't change any of the new improvements you made to the width and wrapping
![Screenshot 2023-06-15 at 5 28 34 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/b0ff3aa8-c320-471c-99fe-0a7e32a83af7)

2023-06-15 21:34 UTC, androche approved these changes
Looks good - that was a tough one to wrangle!  One more comment below, but approving ahead of time!

2023-06-15 22:19 UTC, merged