feat: magnetic adjustments and updates to checkbox
cisco-sbg-ui/magna-react pull request #454
Opened 2023-06-29 14:13 UTC by androche

**Resolves #453 - Magnetic fixes and updates**

- **Breaking change:** Medium is default as per magnetic docs: https://magnetic.cisco.com/0a43ab5cd/p/71e3ca-checkbox-
- Color updates to state as well as similar updates to button styles. (minor color shifts in the figma)

![Screenshot 2023-06-29 at 10 03 38 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/67e34460-f12d-4c0f-a4d2-df3dfd459fcf)
![Screenshot 2023-06-29 at 10 03 58 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/28a5f2c8-4f86-4921-8b06-994bddde23c6)

2023-07-06 18:55 UTC, rwharrisjr requested changes

2023-07-06 18:55 UTC, rwharrisjr commented on framework/components/ACheckbox/ACheckbox.js
> +      small,
nice

2023-07-06 18:55 UTC, rwharrisjr commented on framework/components/ACheckbox/ACheckbox.js
> +    if (small || size === "small") {
I wonder if we can clean this up on line 141 with 
```
boxSize = size === "small" || small ? "small" : size;
{...
className: `${boxClassName} a-${boxSize}-box`
}
```

2023-07-06 19:35 UTC, trent-boyd commented on framework/components/ACheckbox/ACheckbox.js
> +   */ size: PropTypes.oneOf(["default", "small", "medium"])
This might be a linter issue, but there should be a line break here.

```suggestion
   */
   size: PropTypes.oneOf(["default", "small", "medium"])
```

2023-07-06 21:25 UTC, androche commented on framework/components/ACheckbox/ACheckbox.js
> +    if (small || size === "small") {
had to stick "medium" in there bc size might be `undefined` here since it's getting phased out.

2023-07-07 14:42 UTC, rwharrisjr requested changes

2023-07-07 14:42 UTC, rwharrisjr commented on framework/styles/theme/default.scss
> +    "bg--checked--hover": map-get($mds-interactive, "interactive-12"),
Seems to be #7aa7f5 in the magnetic-react lib

2023-07-07 16:24 UTC, androche commented on framework/styles/theme/default.scss
> +    "bg--checked--hover": map-get($mds-interactive, "interactive-12"),
I'd pick the figma over that though, because the same color is consistant for the button hovers #7CADF7

#7aa7f5 is used for "status or state" related blues.  

https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/YNkCw8yeaOOOuvxWtyRz4X/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=15437-56920&mode=design&t=ukinzBOFx3O8SGDU-0

2023-07-07 20:25 UTC, rwharrisjr approved these changes

2023-07-07 20:44 UTC, merged