Remove remaining theming references
cisco-sbg-ui/magna-react pull request #623
Opened 2024-02-20 15:06 UTC by androche

**#617 - Phase 2: Remove theming from individual magna files**

That should do it!

2024-02-23 16:45 UTC, rwharrisjr requested changes

2024-02-23 16:45 UTC, rwharrisjr commented on framework/components/AList/AList.scss
> +    font-weight: unset;
I think this needs a !important

<img width="332" alt="Screenshot 2024-02-23 at 10 14 37 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/23561587/df277590-eb22-41da-8477-c71a0753dcc1">

The third example gets a bolded first item after this change

2024-02-23 16:45 UTC, rwharrisjr commented on framework/components/AMenu/AMenu.scss
> -@include theme("a-menu.a-list") using ($theme) {
The arrows seem to have gotten broken 

<img width="622" alt="Screenshot 2024-02-23 at 10 16 32 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/23561587/e5f809e6-892d-4656-9106-e2e13e23fece">

2024-02-23 16:45 UTC, rwharrisjr commented on framework/components/ASkeleton/ASkeleton.scss
> +      background: linear-gradient(
In light theme this now seems to be a lot less noticeable during the animation

2024-02-23 16:45 UTC, rwharrisjr commented on framework/components/ATimeline/ATimeline.mdx
> +  code={`<ATimeline>
Nice

2024-02-23 16:45 UTC, rwharrisjr commented on framework/styles/utilities/functions.scss
> -@function map-deep-merge($parent-map, $child-map) {
We might want to leave this for now, just in case anyone is using it. But mark it as deprecated so we can get rid of it when we do the first non-beta release

2024-02-27 15:36 UTC, androche commented on framework/components/ASkeleton/ASkeleton.scss
> +      background: linear-gradient(
Yea that's how its been since the initial change over to CDS.  They use different colors than we were have have different animation.  We might be able to tweak ours though, but probably another PR would be good for that

2024-02-27 17:05 UTC, rwharrisjr commented on framework/components/ASkeleton/ASkeleton.scss
> +      background: linear-gradient(
Agreed, new PR

2024-02-27 17:06 UTC, rwharrisjr approved these changes

2024-02-27 17:17 UTC, merged