chore: remove palette, color-helpers, and theme folder
cisco-sbg-ui/magna-react pull request #688
Opened 2024-04-18 15:16 UTC by androche

**Closes #617 - Fiinal stage**

Breaking change to any groups using palette or theme maps

(also fixed icon position in contextual notifications)

**Before**
![Screenshot 2024-04-18 at 11 16 41 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/c5f19cb0-7a54-4509-add9-620b69037a48)

**After**
![Screenshot 2024-04-18 at 11 02 46 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/4efbccb9-7640-4376-a959-6d7664a51f2a)

2024-05-01 18:46 UTC, rwharrisjr requested changes
I think with a note added to the Changelog about the breaking change this is good to go

2024-05-01 18:48 UTC, androche commented
wellll, it severely breaks another team lol. I might hold it for a little while we try to help them transition off of palette, but i also dont want it to sit too long.  Maybe we can check in before 2.0

2024-05-03 15:21 UTC, androche commented
Merging for 2.0 as this will block other PRs.  We've decided to merge for 2.0 with the understanding that other teams can avoid bumping to 2.0 until ready.

2024-05-03 15:46 UTC, rwharrisjr approved these changes

2024-05-03 16:07 UTC, rwharrisjr approved these changes

2024-05-03 16:22 UTC, merged