Add magnetic compliant pagination component
cisco-sbg-ui/magna-react pull request #764
Opened 2024-06-25 18:58 UTC by rwharrisjr

Resolves #763 

![Screenshot 2024-06-25 at 1 52 48 PM](https://github.com/cisco-sbg-ui/magna-react/assets/23561587/d236ec53-d1c4-478c-b8f1-b3c1a730ad11)

The old pagination component doesn't align well to magnetic, in both display, page counts, or style. It also has variants that are not part of the magnetic design.

This PR adds a new `APaginator` component that aligns with the magnetic design. `APagination` should be considered deprecated.

2024-06-28 14:00 UTC, androche reviewed
Wow that was fast!!!  Will look soon - At a quick glance it seem there's some minor differences in figma that could be quickly updated like width of input seems to be 64px, height of buttons 28px, and can remove the 1-15 text altogether.  
<img width="636" alt="Screenshot 2024-06-28 at 9 57 10 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/4f9d3617-ede2-4c5d-83f5-4f568df8d48d">


I'll pull up the other magnetic update documentation as well.

2024-06-28 14:12 UTC, androche requested changes
Update: I see now actually figma leaves out the 1-15 from the magnetic specs so disregard.  Here's a few more specific items from the figma.

2024-06-28 14:12 UTC, androche commented on framework/components/APaginator/APaginator.scss
> +    height: 32px;
Height and width should be `28px`

2024-06-28 14:12 UTC, androche commented on framework/components/APaginator/APaginator.scss
> +            border: 2px solid var(--interact-border-disabled) !important;
control-border-medium-default

2024-06-28 14:31 UTC, androche commented on framework/components/APaginator/APaginator.scss
> +      fill: var(--control-border-default);
interact-icon-weak-default

2024-06-28 14:36 UTC, androche commented on framework/components/APaginator/APaginator.scss
> +
Not in figma, but needs a hover state - probably same as the selected background

<img width="279" alt="Screenshot 2024-06-28 at 10 33 21 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/e56a8dd1-ae42-4e9a-9428-538d9bc1e63b">

<img width="272" alt="Screenshot 2024-06-28 at 10 33 34 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/213d62b0-85d1-4d0d-984c-eb759636e19a">

2024-06-28 17:29 UTC, rwharrisjr commented
@androche the width of the ASelect was intentional, any smaller and when 100 is selected the width changes and the controls move. Decided to avoid that and be slightly different than the figma

2024-06-28 17:54 UTC, androche commented
> @androche the width of the ASelect was intentional, any smaller and when 100 is selected the width changes and the controls move. Decided to avoid that and be slightly different than the figma

Hmm it looks like that would be more related to the padding on `.a-select__selection`

So if you take away the padding on right pushing the icon and similarly left on icon it prevents the jumping
```scss
 .a-select {
      width: 64px;
      .a-icon {
        padding: 0 5px;
      }
      &__selection {
        padding: 0 0 0 8px;
      }
    }
 ```
 
![jumping](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/8e37fb6c-258f-4c75-bbbe-323eca97787f)

2024-07-01 13:52 UTC, androche commented
Added fixes to the button styling and colors:

![Screenshot 2024-07-01 at 9 30 05 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/92508dcb-ea15-47a7-b6b8-a4cb2df78e73)

This is almost there, but it looks like disabled is breaking in this PR.  Currently, implementing disabled should disabled all buttons and controls as seen below. 

![Screenshot 2024-07-01 at 9 49 34 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/9ae9e13a-7de2-4c57-99cb-ac7039cd2e55)

2024-07-08 13:33 UTC, rwharrisjr commented
Fixed the disabled state

2024-07-08 14:43 UTC, androche approved these changes
🎉  Looks/working great! We may want to move over the props to this one (or link it), but we could do that when we remove the old one.

2024-07-08 15:09 UTC, androche approved these changes

2024-07-08 15:10 UTC, merged