refactor: typescript for AAlert, AStep, AToast, and update deprecated…
cisco-sbg-ui/magna-react pull request #798
Opened 2024-07-22 20:08 UTC by androche

2024-07-23 14:18 UTC, rwharrisjr requested changes

2024-07-23 14:57 UTC, androche commented on framework/components/AAlert/AAlert.tsx
> +      dismissible = true,
hmm i didnt even think about supporting both lol. That might be a good middle ground.

2024-07-23 14:59 UTC, rwharrisjr commented on framework/components/AAlert/AAlert.tsx
> +      dismissible = true,
And then we could mark it as deprecated and remove in the eventual 3.0 version

2024-07-25 20:24 UTC, rwharrisjr approved these changes

2024-07-26 14:05 UTC, merged