Feat: Allow custom placeholder components
cisco-sbg-ui/magna-react pull request #830
Opened 2024-08-08 19:33 UTC by jonathanmcsweet

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows semantic commit message guidelines
- [ ] The changes are documented in component docs and changelog
- [ ] The ESLint plugin has been updated if a new component is added
- [ ] Test have been added or modified, if appropriate
- [ ] Has been verified locally
- [ ] The component should accept a class name as a prop, if appropriate
- [ ] The component should accept a forward ref, if appropriate

**What kind of change does this PR introduce?** 
Feature: Updated ASelect placeholder prop to take a component or a string and also added a code example

**What is the current behavior?**
- Currently the placeholder prop only accepts a string although you can pass a component but will get an error in the browser console

**What is the new behavior (if this is a feature change)?**
- The new behavior allows for the placeholder prop on ASelect to render a custom component or a string

**Does this PR introduce a breaking change?** 
- This should be entirely backwards compatible with previous use cases

2024-08-08 20:49 UTC, rwharrisjr commented
@jonathanmcsweet  the type in `types.ts` needs to be updated as well

2024-08-09 13:49 UTC, rwharrisjr requested changes

2024-08-09 13:49 UTC, rwharrisjr commented on framework/components/ASelect/ASelect.js
> +    const eitherPlaceholder =
small nitpick on magna code patterns - other components will do something like

`placeholder: propsPlaceholder` in the component props, then `const eitherPlaceholder` could be `const placeholder`

2024-08-13 18:18 UTC, jonathanmcsweet commented on framework/components/ASelect/ASelect.js
> +    const eitherPlaceholder =
- [ ] Use standard convention for props placeholder

2024-08-13 21:07 UTC, rwharrisjr approved these changes

2024-08-14 17:01 UTC, merged