Add trial arrow icon
cisco-sbg-ui/magna-react pull request #867
Opened 2024-09-11 17:23 UTC by rwharrisjr

fyi @danlesko 

![Screenshot 2024-09-11 at 12 21 44 PM](https://github.com/user-attachments/assets/3c5cf775-f689-4829-8f56-62e5d1600987)

2024-09-11 17:29 UTC, danlesko approved these changes
Thanks for the quick update!

2024-09-11 17:48 UTC, danlesko requested changes
Being told we actually want to use the updated phosphor "cursor" icon instead. 

https://phosphoricons.com/?weight=%22bold%22&q=%22mouse%22&size=16

2024-09-11 19:12 UTC, rwharrisjr commented
@danlesko updated pr to add `cursor` icon

2024-09-12 13:10 UTC, androche approved these changes

2024-09-12 15:52 UTC, merged