Use floating-ui for tooltips
cisco-sbg-ui/magna-react pull request #892
Opened 2024-09-18 22:15 UTC by rwharrisjr

2024-09-20 14:09 UTC, androche reviewed
Love all the CSS deletions and its functional!!! :)     More detailed comments below.  We should definitely take our time with this one -  I see how its definitely a bit more tricky than the dropdown one somehow!!

2024-09-20 14:09 UTC, androche commented on framework/components/ATriggerTooltip/types.ts
> +    placement?: Placement;
Probably the most complicated task to look into.

-------

Just to note this is a breaking change for other repos which are using our exported type of APlacement.  We'll either need to figure out a way to export floating-ui's `Placement` type where we export APlacement now which will break AMenu's placement likely, or find a way to extend.  Or map this type back to APlacement somehow. 
 Luckily this can be tested in xdr-components. 
```
Type 'APlacement' is not assignable to type 'Placement | undefined'.
  Type '"top-right"' is not assignable to type 'Placement | undefined'.

34       placement={tooltipPlacement}
         ~~~~~~~~~
```

2024-09-20 14:09 UTC, androche commented on framework/components/ATooltip/ATooltip.scss
> -  font-size: $font-size--sm;
Quite a few issues over in xdr-components if you can test against that. 
![Screenshot 2024-09-20 at 10 05 06 AM](https://github.com/user-attachments/assets/32fb54f8-bf13-4ed9-a415-9adf8cbb758a)
![Screenshot 2024-09-20 at 10 04 47 AM](https://github.com/user-attachments/assets/670d4073-7705-4da8-8ee2-628f553e0838)

2024-09-20 14:09 UTC, androche commented on framework/components/ATooltip/useFloatingTooltip.tsx
> +    onOpenChange,
Can we speed up the opening of the tooltip? As a user I found it to be slightly slower than I'm used to which caused some micro annoyances lol

2024-09-20 15:27 UTC, rwharrisjr commented on framework/components/ATooltip/utils.js
> +export const mapPlacement = (placement) => {
I think this is working as expected - in current magna the edge detection is at the panel container boundary. So it looks like it's center for `bottom-right`.

As for left vs right, it aligns where the "shift" "starts". So bottom-left would start the tooltip at the left edge of the anchor. And opposite for right

2024-09-20 15:31 UTC, rwharrisjr commented on framework/components/AFloatingMenu/types.ts
> +  ignoreOutsideClick?: boolean;
Added

2024-09-20 15:36 UTC, rwharrisjr commented on framework/components/ATriggerTooltip/types.ts
> +    placement?: Placement;
Reworked it so it uses `APlacement` for our type, then maps properly to floating-ui's Placement options

2024-09-20 15:59 UTC, rwharrisjr commented on framework/components/ATooltip/ATooltip.scss
> -  font-size: $font-size--sm;
Resolved by importing tooltip css in ATriggerTooltip, since it bypasses ATooltip now

2024-09-20 16:14 UTC, rwharrisjr commented on framework/components/ATooltipBase/types.ts
> +  children: React.ReactNode;
Updated

2024-09-20 16:14 UTC, rwharrisjr commented on framework/components/AFloatingMenu/types.ts
>    className?: string;
Updated

2024-09-20 16:25 UTC, rwharrisjr commented on framework/components/ATriggerTooltip/types.ts
> +import {ATooltipBaseProps} from "../ATooltipBase/types";
Cleaned up

2024-09-24 14:37 UTC, androche commented on framework/components/ATooltip/utils.js
> +export const mapPlacement = (placement) => {
Yea I guess that must be it - but at same time I don't really get how these are the same both are `bottom-left`. 

![Screenshot 2024-09-24 at 10 27 41 AM](https://github.com/user-attachments/assets/070ccb13-2d06-427d-8b28-7976a707f008)
![Screenshot 2024-09-24 at 10 27 50 AM](https://github.com/user-attachments/assets/9c264caa-e3de-4461-8967-1a7b998c6033)

Either way, this for example would the arrow be closer to the bottom.  I wonder if we should add some more placeholder text to the tooltip so we can visualize it better?
![Screenshot 2024-09-24 at 10 28 01 AM](https://github.com/user-attachments/assets/182c3d81-adf0-41c0-9289-bfe663a1c867)

2024-09-24 14:40 UTC, androche commented on framework/components/ATooltipBase/types.ts
> +    style: React.CSSProperties;
style can be deleted

2024-09-24 15:40 UTC, androche commented on framework/components/ATooltip/types.ts
> +  ATooltipBaseProps,
Ok this will do it if you copy paste in `ATooltip/types`
```
import {AFloatingBaseProps} from "../AFloatingBase/types";

export type ATooltipProps = Omit<
  AFloatingBaseProps,
  "trigger" | "interactive"
> & {
  /**
   * Override the default max-width
   */
  maxWidth?: string;
};
```

We are losing Override on this so that's something to think about.

Verified the type addition and omit works:
![Screenshot 2024-09-24 at 11 38 38 AM](https://github.com/user-attachments/assets/88fdcabd-371c-47d4-b003-fae9ddf101dc)

2024-09-24 15:47 UTC, rwharrisjr commented on framework/components/ATooltip/utils.js
> +export const mapPlacement = (placement) => {
Updated examples to help identify how these work. The main problem is previously the tooltips were too short to demonstrate the effects

2024-09-24 15:47 UTC, rwharrisjr commented on framework/components/ATooltipBase/types.ts
> +    style: React.CSSProperties;
Done

2024-09-24 15:50 UTC, androche commented on framework/components/ATooltip/types.ts
> +  ATooltipBaseProps,
Actually we still get Override in the baseProps so that's good.  I highly doubt there's an overrlapping maxWidth types 😄

2024-09-24 19:02 UTC, androche commented on framework/components/ACopyButton/ACopyButton.scss
> +    svg {
Just checking to see if you wanted this in here or separate PR

2024-09-24 19:03 UTC, androche commented on framework/components/AFloatingBase/types.ts
> +    anchorRef: React.RefObject<HTMLElement>;
This is marked as required so its giving ts errors in other envs

2024-09-24 19:33 UTC, rwharrisjr commented on framework/components/ACopyButton/ACopyButton.scss
> +    svg {
Yes, the arrow has to be selected differently. And while I was in there I updated the icon size to match the magnetic spec

2024-09-25 13:25 UTC, androche approved these changes

2024-09-25 13:26 UTC, androche requested changes
Oops! One more

2024-09-25 13:26 UTC, androche commented
IM is getting an error on content prop:

```
TS2322: Type 'ReactNode' is not assignable to type 'string | (string & ReactElement<any, string | JSXElementConstructor<any>>) | (string & Iterable<ReactNode>) | (string & ReactPortal) | undefined'.
  Type 'null' is not assignable to type 'string | (string & ReactElement<any, string | JSXElementConstructor<any>>) | (string & Iterable<ReactNode>) | (string & ReactPortal) | undefined'.
    66 |       placement={tooltipPlacement}
    67 |       disabled={!shouldShowTooltip}
  > 68 |       content={tooltipText || children}>
       |       ^^^^^^^
    69 |       <ATag
    70 |         ref={ref}
    71 |         className={classNames(css.tag, "mr-1 mb-2")}
    ```

2024-10-07 19:14 UTC, androche approved these changes
🎉 🎉 🎉

2024-10-07 19:22 UTC, merged