Convert APopover to use AFloatingBase
cisco-sbg-ui/magna-react pull request #914
Opened 2024-10-08 21:54 UTC by rwharrisjr

2024-10-11 13:47 UTC, androche requested changes
Good news is it works 😄 
A few issues came up in other envs:

1. Rebase and run `npm run lint` not sure what will show up there.  This will also give the labels fixes I believe for oak that keep failing. 
2. Run in oak from there and there appears to be a role menu issue where the element is now nested - wonder if we can bring it to the top level or if the tests need to be changed
Failing on getbyrole menu
![Screenshot 2024-10-11 at 9 26 31 AM](https://github.com/user-attachments/assets/e206df27-518a-4b49-88ec-87a25bc8f896)

Current implementation on INT
![Screenshot 2024-10-11 at 9 42 27 AM](https://github.com/user-attachments/assets/9ee9c909-73f6-4f34-9443-f1661a287aa1)

3. IM has some failures around assigneeAvatarTooltip which I thought we looked into last week, but this does appear to be a new error. 

4. We might consider taking out the console.warn for toast as the warning is triggering test errors.  Maybe a console.log in that case would still be good.

5. Tooltip vs popover issues:

![Screenshot 2024-10-11 at 9 18 29 AM](https://github.com/user-attachments/assets/94672a51-8b79-48be-b9fc-b59e3947a553)
![Screenshot 2024-10-11 at 9 17 57 AM](https://github.com/user-attachments/assets/487174d5-ccb4-44b1-aec0-7bef5e680177)

2024-10-11 14:02 UTC, rwharrisjr commented
`npm run lint` doesn't return any issues

2024-10-11 19:57 UTC, androche approved these changes
Approving ahead of time, but see notes below before merging! 
- Remove C type
- IM is passing!  🎉 
- Oak still has same menu error so not sure what's going on there?  Might be worth merging and seeing what's left over there after the toast fix below:
- If you could also sneak in the console.log on the toast here that would be good too.

2024-10-11 19:57 UTC, androche commented on framework/components/APopover/APopover.d.ts
>  declare const APopover: <C extends React.ElementType = "div">(
Getting a C is defined but never used

2024-10-14 14:05 UTC, androche approved these changes

2024-10-14 14:08 UTC, merged