Add AEmptyState horizontal layout; align magnetic small/medium/large sizes
cisco-sbg-ui/magna-react pull request #917
Opened 2024-10-09 22:04 UTC by rwharrisjr

Magnetic figma shows smaller icon sizes and a larger gap under the label. Note this does not align with current CDS implementation, but is less comically large than before. 

![Screenshot 2024-10-09 at 5 03 51 PM](https://github.com/user-attachments/assets/730face1-7e2f-490d-8885-eaf76c5f83f9)

2024-10-10 16:03 UTC, brennarvo approved these changes
This looks good to me. @androche, you might want to double check me on the icon resizing though

2024-10-10 16:03 UTC, brennarvo commented on framework/components/AEmptyState/AEmptyState.js
> +
Nice refactor moving this out of the component 👍

2024-10-10 16:03 UTC, brennarvo commented on framework/components/AEmptyState/AEmptyState.scss
> +    margin: 0 0 12px 0;
Is the bottom-margin here coincidental with the `$icon-xs` sass variable? Only wondering in case it should always be synced with the size of the small icon.

2024-10-10 16:17 UTC, rwharrisjr commented on framework/components/AEmptyState/AEmptyState.scss
> +    margin: 0 0 12px 0;
coincidental, that just seemed to be the gap that the figma had. Combined with the line-height for each size it fit

2024-10-14 14:39 UTC, androche requested changes
Oops - sorry i missed this message last week.

Ok so to be specific:

Technically, starting with a medium size, the icon size should be (according to figma) 52.93.  BUT the catch is our icon is actually smaller than the figma even though we might specify 53px in css is clocking in  at `43px`.
![Screenshot 2024-10-14 at 10 34 36 AM](https://github.com/user-attachments/assets/bd6617f7-9b2a-4041-945a-e829dba7aacf)

We'll need to adjust our css to get it as close to 53 as possible, which in our code is `$icon-md: 65px;` and the surrounding icons and sizes need to be adjusted to this.
![Screenshot 2024-10-14 at 10 37 45 AM](https://github.com/user-attachments/assets/f8618c6f-f40d-4171-a2dd-f6b4f20a8d74)


@rwharrisjr happy to help gather the rest of these numbers while you make these adjustments to medium


Update - I was viewing the icon in the sidebar which still included additional padding so these number are incorrect so please disregard - I sent over adjustments with correct pxs.

2024-10-14 16:48 UTC, androche requested changes

2024-10-14 16:48 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
>        font-size: 24px;
`font-size: 18px`

2024-10-14 16:48 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
>        font-size: 18px;
`font-size: 16px"

2024-10-14 16:48 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
> +      margin-left: 12px;
this is actually `40px` for large, but this would need to be adjusted for each medium and small

2024-10-14 16:48 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
> +      margin-left: 12px;
What might be easier is doing margin right adjustments on the icon container itself since we already have code separated out for that. 

.a-empty-state--large .a-empty-state__container {
    height: 224px;
    width: 224px;
    margin-right: 40px;
}

2024-10-14 16:48 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
> +    margin: 0 0 12px 0;
On horizontal this is actually 8px on the large going smaller with each size.    It might be better to do label space in the sizing css already set up (mentioned below) and just override this if you didn't want to spend more time on it.

2024-10-14 16:49 UTC, androche commented on framework/components/AEmptyState/AEmptyState.scss
> +      margin-left: 12px;
Decreasing the margin for each size variation

2024-10-14 19:35 UTC, androche approved these changes
Looks great!!

@brennarvo please ignore extra review prompt - I clicked the wrong button! :)

2024-10-14 19:36 UTC, merged