Allow ADropdown to be controlled externally
cisco-sbg-ui/magna-react pull request #961
Opened 2024-11-13 19:34 UTC by rwharrisjr

Needed for integration with some UI elements that auto open dropdowns

2024-12-04 15:11 UTC, rwharrisjr commented on framework/components/ADropdown/ADropdown.tsx
> +    const openState = open || isOpen;
This logic would change my intention. My idea was that the open state can be controlled by an external prop, but otherwise the menu should respond to the normal close events (click outside, click on button, escape key). 

I think normal close behavior is desired vs having to have the consuming side manage closing of the menu, particularly in instances that some kind of UI automation opens the menu for the user and intends for the user to then interact with the menu

2024-12-04 15:49 UTC, androche commented on framework/components/ADropdown/ADropdown.mdx
> +<Playground
When i'm clicking open one, it doesn't toggle like the others. Could be missing the use case for open only, but seems like it should probably just toggle like the others' behavior:

![toggle](https://github.com/user-attachments/assets/6144dbce-b530-42c6-ac4e-18714198e5f3)

2024-12-04 15:50 UTC, androche commented
Lastly, if it could just be tested in IM or somewhere that is already using ADropdown and run TS in there that would be good

2024-12-04 15:54 UTC, rwharrisjr commented on framework/components/ADropdown/ADropdown.mdx
> +<Playground
It won't be a button that'll set the open state for the main use case. And in the case of an external button, it would be the consumer's responsibility to toggle the state to false

2024-12-04 16:17 UTC, androche approved these changes
![approved](https://github.com/user-attachments/assets/4e92507a-8032-4fda-8cfd-120926486ad2)

2024-12-04 17:15 UTC, mvelkCisco commented
I just came across this randomly:

> The menu will respect `true` for `isOpen`, but otherwise handle clicks of menu items and outside click as normal.

Does that mean that `isOpen={false}` will not close the dropdown? Because if so, that's very confusing. 

All we need is the dropdown to respect the `isOpen` fully when it's controlled from outside. Otherwise we will have inconsistent internal state with whatever value is in the `isOpen={myControledBooelan}` and the consumers would need to do some awkward state syncing too.

2024-12-04 17:23 UTC, rwharrisjr commented
Setting `isOpen={false}` will close the menu, if it was opened by previously being true. However, if the menu is opened by user click it will ignore `isOpen={false}` and use its internal state. The required `onClose` callback syncs the `myControledBooelan` state to avoid the inconsistency. I think.


```
() => {
  const ref = useRef(null);
  const [isOpen, setIsOpen] = useState(true);
  
  setTimeout(() => {setIsOpen(false)}, 3000)

return (

<div>
  <ADropdown
    ref={ref}
    isOpen={isOpen}
    onClose={() => {
      setIsOpen(false);
    }}
    title="Can be opened by a state prop">
    <AListItem
      onClick={() => {
        console.log(ref.current);
      }}>
      List item
    </AListItem>
    <AListItem
      onClick={() => {
        console.log(ref.current);
      }}>
      List item
    </AListItem>
  </ADropdown>
</div>

);
}
```

2024-12-04 17:27 UTC, brennarvo commented
@rwharrisjr @mvelkCisco the dilemma here is that if we allow `isOpen` to fully control the state, then a consumer of `ADropdown` then has to handle all the different closing scenarios (e.g. outside clicks, <kbd>esc</kbd> keypresses, closing after clicking a menu item, etc.).

I think a way we can handle both of these cases is like this:

```typescript
function Example() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <ADropdown
      isOpen={isOpen}
      // `onClose` is called on outside clicks, ESC keypresses, on dropdown item clicks, etc.
      onClose={() => setIsOpen(false)}
    />
  )
}
```

In this example, the `isOpen` prop should always be respected, meaning if I hardcoded `false`, it would *never* open. However — the `onClose` prop would allow a consumer to handle all the different closing scenarios (outside click, <kbd>esc</kbd> keypresses, etc.)

2024-12-04 17:30 UTC, mvelkCisco commented
@rwharrisjr @brennarvo I think you both proposing the same thing. I think this makes sense. Sorry, it's a bit late in the day for me :D

2024-12-04 17:32 UTC, brennarvo commented
@mvelkCisco I think mine is slightly different. @rwharrisjr is suggesting that even if we pass `isOpen={false}` to the menu, it would still open up if the user re-clicked the menu itself.

To address that with my suggestion, we'd also need an `onOpen` prop:

```tsx
function Example() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <AButton onClick={() => setIsOpen(true)}>Open</AButton>
      <ADropdown
        isOpen={isOpen}
        // `onOpen` is called whenever the internal `ADropdown` implementation determines it's trying to be opened
        onOpen={() => setIsOpen(true)}
        // `onClose` is called on outside clicks, ESC key, and when a dropdown item is clicked, etc.
        onClose={() => setIsOpen(false)}
      />
    </>
  );
}
```

2024-12-04 17:40 UTC, mvelkCisco commented
Right. As a consumer I would expect that the menu does not close when `isOpen={true}`, unless I provide that `onClose={() => setIsOpen(false)}` callback. If you internally call that `onClose` instead of actually closing using your internal state, we can have a good and consistent data flow on both sides. If that's the case, and it's provided as an example in the documentation I think we are good. 

If the internal and external state get out of sync just because the the `onClose` was not provided, that's what can cause unexpected bugs. I don't think all developers will realize that clicking outside the menu will close it for them, and that the states would diverge.

2024-12-04 18:08 UTC, rwharrisjr commented
I wonder if it would be overkill to add an error/warning for "if `isOpen` prop exists on props check that `onClose` also exists, else throw error"?

2024-12-04 18:18 UTC, mvelkCisco commented
> I wonder if it would be overkill to add an error/warning for "if `isOpen` prop exists on props check that `onClose` also exists, else throw error"?

I think it wouldn't hurt. If the consumer defines `onClick={() => setIsOpen(prev => !prev)}`, they still might not notice an issue.

It would be nice to restrict this by TS.

2024-12-09 19:28 UTC, androche requested changes

2024-12-09 19:28 UTC, androche commented on framework/components/ADropdown/ADropdown.tsx
> +export type MustExist<T, ErrorMessage extends string> = T extends () => void
In the example  `() => void` would actually be the type we would _not_ want it to allow.   So in example it was dont allow any arrays, so it was `T extends any[]` -> pass in array -> ts error.  

I assumed something like `T extends undefined` would error TS - it does when you manually pass in undefined, but not the value from the prop.

BUT none of it works TS wise so I guess it doesnt matter.  This could probably all be deleted to just show the console error. lol  Or at least change it to `undefined` so we can pretend

2024-12-09 19:28 UTC, androche commented on framework/components/ADropdown/ADropdown.tsx
> +    console.error("ADropdown: onClose must exist with isOpen", arg);
We're getting an infinite loop here in other envs:

![Screenshot 2024-12-09 at 2 20 37 PM](https://github.com/user-attachments/assets/6d98ed5f-bb39-4454-8a36-48ffccc275f0)

2024-12-09 19:28 UTC, androche commented on framework/components/ADropdown/ADropdown.tsx
>  import useFloatingDropdown from "../AFloatingMenu/useFloatingDropdown";
No Idea why styling was impacted 


![Screenshot 2024-12-09 at 2 25 57 PM](https://github.com/user-attachments/assets/ca09ab41-5044-44f7-9df0-d7894e46ebf0)


Verified in IM:
![Screenshot 2024-12-09 at 2 15 29 PM](https://github.com/user-attachments/assets/a46963aa-3494-4522-b1f3-ee50dc5c4ac4)

2024-12-09 22:10 UTC, androche approved these changes

2024-12-10 19:13 UTC, merged