Feature: AUpload component
cisco-sbg-ui/magna-react pull request #979
Opened 2024-12-05 21:47 UTC by trent-boyd

- **chore: add dependency: react-dropzone**
- **chore: add dependency: classnames**
- **chore: remove stray console log**
- **feat: add basic AUpload component**

**Please check if the PR fulfills these requirements**

- [ ] This change has been run and tested against at least 2 typescript applications
- [ ] This change passed unit tests in the applications the build was tested against
- [ ] The changes are documented in component docs and changelog
- [ ] Test have been added or modified, if appropriate
- [ ] Convert component to tsx, if reasonable
  
For new components
- [ ] The component should be in typescript
- [ ] The component should accept a class name as a prop, if appropriate
- [ ] The component should accept a forward ref, if appropriate
- [ ] Add tests in typescript, cypress/tests/*, if reasonable

**Does this PR introduce a breaking change?** 

No

**Other information**:

The design of this component appears incomplete. The [Drag & Drop](https://www.figma.com/design/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=99416-135350&t=LpIYiZu3d0Beq49p-4) variant does not indicate that a file has been uploaded. There is no error state.

This PR does not include other upload variants such as Avatar and List. Those can be added in the future.

2024-12-05 21:50 UTC, trent-boyd commented on framework/components/AUpload/AUpload.js
> +  const [file, setFile] = React.useState(null);
`file` isn't used here because there is no design for it. I will ask Design how this is supposed to look after a file is uploaded.

2024-12-05 21:51 UTC, trent-boyd commented on framework/components/ATriggerBase/ATriggerBase.tsx
> -
I should move this change to another PR. This one will be open for awhile.

2024-12-05 23:10 UTC, wlorand3 commented on framework/components/AUpload/AUpload.js
> +  const [file, setFile] = React.useState(null);
Hiya Trent,
Stoked you are making good progress on this;
Re: "ask Design", Alana and Derrick may be good  UXers that are close to this design and it's initial XDR implementation for the new Google Cloud Platform (GCP) Module Integration (SCA Convergence project);

Here's the latest Q2 FY25 Figma file for GCP that shows current thinking on the various states for File Upload including filename in a textbox with trash can icon 
https://www.figma.com/design/QZvPOfFmZ3v65Bj8xoxJ9i/GCP-Integration-Q2-Version?node-id=0-1&node-type=canvas&t=gabiBdsUxn7NhQjs-0

hope this helps a bit...

2024-12-06 13:35 UTC, jonathanmcsweet commented on framework/components/AUpload/AUpload.js
> +  const [file, setFile] = React.useState(null);
File can be passed to some sort of callback for developers to use. It's important as we may need to store the file name for later use. One example would be showing the file name to the user after they've saved their Administration Integration and we need to now render the saved data so the user can remember which file name they uploaded if they're dealing with numerous uploads

2024-12-06 13:47 UTC, jonathanmcsweet commented on framework/components/AUpload/AUpload.js
> +  supplementalText: PropTypes.node,
Proptypes are getting deprecated in React 19 FYI. I know this is a draft and you're planning on writing it in Typescript, but I figured I'd give you another incentive

2024-12-06 13:54 UTC, jonathanmcsweet commented on framework/components/AUpload/AUpload.js
> +      setFile(extendedDroppedFile);
Can we give the developer a callback prop and return them:

```
return {
  fileList,
  reader,
  event,
}
```

2024-12-16 22:50 UTC, trent-boyd commented on framework/components/ALoader/ALoader.mdx
> +_DEPRECATED_ use `AProgressbar or ASpinner`
I spelled it in all camelcase and got a warning about it, so I figured I'd fix it here too.

2024-12-18 05:01 UTC, wlorand3 reviewed
Looking really good on vercel preview - and looks to work as designed for the json file use-case -- left a few small comments on tests, trash icon - Looks good to me -- leaving this as comment as is currently draft pr with failing CI

2024-12-18 15:41 UTC, trent-boyd commented on framework/components/AUpload/AUpload.tsx
> +                  <AIcon size={18}>trash-simple</AIcon>
I was kind of thinking the same thing. Since the designs are still being developed, I'll change it to `trash` and see if anybody complains later. Quick fix either way.

2024-12-18 15:58 UTC, trent-boyd commented on framework/components/AUpload/AUpload.js
> +      setFile(extendedDroppedFile);
@jonathanmcsweet It makes more sense now to export the `extendDroppedFile` function for you to import. You can use it in the first File returned by `dropzoneProps.onDrop`, `dropzoneProps.onDropAccepted`, `dropzoneProps.onDropRejected`

2024-12-18 19:25 UTC, androche requested changes
Very cool!!  Just a few small things noted,  but it looks and works great!! 

I tried to test on IM, but seemed to have unrelated issues again today over there, however I did bring it into x**-components and it worked well!  I do see some "Content Security Policy" warnings in the console after an update, but figured that's something that will magically get worked out when actually in use.

2024-12-18 19:28 UTC, jonathanmcsweet approved these changes
The code and Playground all look great. My only issue is that I've been unable to test it locally by running `pnpm link ../magna-react` inside of securex-ui-monorepo

This may be a PNPM issue as it seems to be more non-deterministic these days, so if you can verify that it is exported properly from Magna React I should be able to use this once it's published. 

Bellow is the error below. It seems to think it's not exported even though I verified that it is inside th magna-react/lib folder
<img width="946" alt="Screenshot 2024-12-18 at 2 28 45 PM" src="https://github.com/user-attachments/assets/15003367-c6e5-47b5-a26b-104088fbb971" />

2024-12-18 19:41 UTC, androche commented
@jonathanmcsweet can you try running `npm pack` instead and installing that way: https://github.com/cisco-sbg-ui/magna-react?tab=readme-ov-file#integration-testing

It eliminates weird situations, but also since this PR has dependencies that would need to be downloaded linking probably would still complain even if it was working!

2024-12-19 16:41 UTC, trent-boyd commented on framework/components/AUpload/AUpload.cy.js
> +      cy.get(".a-upload").should("have.class", "test-class");
Yeah, I caught this after I pushed. A fix is already up!

2024-12-19 16:41 UTC, trent-boyd commented on framework/components/AUpload/AUpload.tsx
> +                  <AIcon size={18}>trash-simple</AIcon>
Handled!

2024-12-19 16:52 UTC, trent-boyd commented on framework/components/AUpload/AUpload.tsx
> +interface AUploadProps {
Couldn't sworn the props were still working for me after I defined the interface and added comments 🤔

I'll take a look!

2024-12-19 16:54 UTC, trent-boyd commented on framework/components/AUpload/AUpload.tsx
> +export function extendDroppedFileInfo(file?: File): ExtendedFile | undefined {
I hear that. I think I'm a loner in relying on function hoisting to do the work here, but I prefer it to be module-scoped instead of moving out to a random single-use utils file.

2024-12-19 16:56 UTC, trent-boyd commented on framework/components/AUpload/AUpload.tsx
> +const AUpload: React.FC<AUploadProps> = ({
Ah, good to know. I'll add in a `style` or spread if I can so we can customize the outer element a bit more.

Regarding a `forwardRef`... I don't know what we'd forward that ref to. Outer element or inner `input` element?

2024-12-19 16:56 UTC, trent-boyd commented on framework/components/AUpload/AUpload.mdx
> +<Playground
I'll definitely have a looksie.

2024-12-19 16:57 UTC, trent-boyd commented
@jonathanmcsweet I assumed it might be related to type exports in my code, but what @androche said is probably correct.

2024-12-19 17:10 UTC, androche commented on framework/components/AUpload/AUpload.tsx
> +const AUpload: React.FC<AUploadProps> = ({
Well those types will come out-of-the-box with the `ComponentPropsWithRef` type so you wouldn't need to add it manually.

For `forwardRef` yea i'm not sure either tbh - I would say the outer, but... I could see a case for it going in `ACardBasic`...  @rwharrisjr  Can you weigh in on this one?

2025-01-06 19:28 UTC, androche approved these changes
Pulled and tested locally and verified in another app. Works really well!!  🎉

2025-01-06 19:48 UTC, merged