XDR-5679 Shared Component: Tabbed Card Stepper
cisco-sbg-ui/magna-react pull request #983
Opened 2024-12-17 20:18 UTC by jflook10

**Please check if the PR fulfills these requirements**
Create a stepper card. 

- [ ] This change has been run and tested against at least 1 typescript application.  (If extensive change, 2 is best)
- [ ] This change passed unit tests in the applications the build was tested against
- [ ] The changes are documented in component docs and changelog
- [ ] Test have been added or modified, if appropriate
- [ ] Convert component to tsx, if reasonable
  
For new components
- [x] The component should be in typescript
- [x] The component should accept a class name as a prop, if appropriate
- [x] The component should accept a forward ref, if appropriate
- [ ] Add tests in typescript, cypress/tests/*, if reasonable

**Does this PR introduce a breaking change?** 
N/A

**Other information**:
https://cisco-sbg.atlassian.net/browse/XDR-15679

2025-01-15 16:27 UTC, androche requested changes
WOW its incredible how clean this is with all the options offered!!! 🥇 🥇   A couple notes, some questions, and adjustments below.  Tested on IM as well!

2025-01-15 16:27 UTC, androche commented on framework/components/AStepperCard/AStepperCard.tsx
> +            <AStep
It looks like step props somehow might not be getting passed through to `AStep` for some props.   For example, It does work for `showIconOnVisited`, but then I added disabled here on 2nd one, but its still appearing as active:
![Screenshot 2025-01-15 at 11 06 55 AM](https://github.com/user-attachments/assets/1e465d10-4120-44ce-9883-4ebdd9830cbd)

2025-01-15 16:27 UTC, androche commented on framework/components/AStepperCard/AStepperCard.tsx
> +      <ACardContainer className="a-stepper-card-container pa-0" style={{height: "100%"}} ref={ref} {...rest}>
There appears to be some jumping around when there is less content.  I see in the designs there is some sort of container management - also based on it scrolling when content gets too long.  I wonder if we should add a set height here or no.  Or if we should have users manage it. I cant really decide! My gut says we give a min height or maybe we need to ask design.
![Screenshot 2025-01-15 at 11 15 00 AM](https://github.com/user-attachments/assets/6eb76e39-1e9e-4041-9680-9cfd8d7d9739)

Here it is in IM for example: 

![Screenshot 2025-01-15 at 11 18 04 AM](https://github.com/user-attachments/assets/69e44661-33b9-4881-9a53-30717b1faf20)

2025-01-15 16:27 UTC, androche commented on framework/components/AStepperCard/AStepperCardContent.tsx
> +const AStepperCardContent = forwardRef<HTMLDivElement, AStepperCardContentProps>(
Scrolling looks great!

2025-01-15 16:27 UTC, androche commented on framework/components/AStepperCard/AStepperCard.mdx
> +
Maybe it would be good to add a link to AStepper props in docs so people can reference AStepper props.

2025-01-15 21:27 UTC, rwharrisjr commented on framework/components/AStepperCard/AStepperCard.tsx
> +        <ACol cols="4" className="a-stepper__card--col dark-cool-grey white--text text-center pr-0">
We do typically try to start with a "root" class like `.a-stepper-card`.

Since the root element is `<ACardContainer>`, I'd set `.a-stepper-card` to it as the root class - since that is in line with the component name.

Then the `ACol` I'd have `.a-stepper-card__col`, since that's a direct child 

That follows the pattern that's (mostly) used elsewhere in magna

2025-01-15 22:08 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCard.tsx
> +        <ACol cols="4" className="a-stepper__card--col dark-cool-grey white--text text-center pr-0">
I removed the dark-cool-gray and white--text. Neither were actually working- thanks for catching that :)

2025-01-15 22:10 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCard.tsx
> +              <AStepTitle className="AStepTitle">
deleted 👍

2025-01-16 14:29 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCardContent.tsx
> +              {  onCancel && <AButton medium tertiary onClick={onCancel} data-testid="aStepperCardContent-button-cancel">
Since the dev using this component can't pass down a data-testid to the button, would we want to add one for them or qa to hook into? There is likely to be one stepper per page so the id would be fairly unique. And they can always create a custom footer if the testid or button functionality isn't working as needed. 

I could also create a props object for the three buttons that included a test id and text value?

2025-01-16 15:01 UTC, androche commented on framework/components/AStepperCard/AStepperCardContent.tsx
> +              {  onCancel && <AButton medium tertiary onClick={onCancel} data-testid="aStepperCardContent-button-cancel">
Yea because they will want to create their own names.  It might be good to do props object as seen in Drawer: https://github.com/cisco-sbg-ui/magna-react/blob/main/framework/components/ADrawer/types.ts#L205

2025-01-16 15:09 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCard.tsx
> +      <ACardContainer className="a-stepper-card-container pa-0" style={{height: "100%"}} ref={ref} {...rest}>
Yea, min-height seems like a flexible happy medium :)

2025-01-16 16:54 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCard.tsx
> +            <AStep
Good catch, I have updated the props so now the steps array will accept/spread the step props.

2025-01-16 21:41 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCardContent.tsx
> +              {  onCancel && <AButton medium tertiary onClick={onCancel} data-testid="aStepperCardContent-button-cancel">
updated- only thing I am not comfortable with is the type declaration and the way it is rendering in the docs. It makes me think that the declaration is incorrect. 

ex: backButtonProps?: AButtonProps<C>[]; 
renders as: AButtonProps<"div">[]

2025-01-17 14:11 UTC, androche commented on framework/components/AStepperCard/AStepperCardContent.tsx
> +              {  onCancel && <AButton medium tertiary onClick={onCancel} data-testid="aStepperCardContent-button-cancel">
Ohh, and looks like it's actually worse in Drawer component. lol.  We should probably open a ticket to figure out how to get it more clear for users.
![Screenshot 2025-01-17 at 9 09 21 AM](https://github.com/user-attachments/assets/f55a2e50-c5c1-4dc8-8423-509ea2f93906)

2025-01-17 16:16 UTC, rwharrisjr commented on cypress/tests/AStepperCard.cy.tsx
> +    const ContentFooter = () => <ACardFooter className="ma-3" data-testid="aStepper-contentFooter-custom">
Nothing to change now, just for future reference - in some of the other component tests we take the component definition out of the actual test block so it can be reused. Here it's not reused so it's fine. Just mentioning in case you look through other tests.

2025-01-17 16:22 UTC, rwharrisjr requested changes

2025-01-17 16:22 UTC, rwharrisjr commented on framework/components/AStepperCard/AStepperCard.scss
> +    &--col {
Typically we use `&--<name>` for something like a modifier vs a dom element. Like `&--primary` in `AButton`

2025-01-17 16:22 UTC, rwharrisjr commented on framework/components/AStepperCard/AStepperCard.scss
> +    &--footer {
Same as the `&--col` comment above

2025-01-17 16:34 UTC, androche commented on framework/components/AStepperCard/AStepperCard.scss
> +    &--col {
I probably led her astray there with the `--` in my earlier comment show a nesting technique example

2025-01-17 18:49 UTC, jflook10 commented on framework/components/AStepperCard/AStepperCard.scss
> +    &--col {
Updated to a "__" for both instances. That fits the pattern, right? 

&__col, &__footer

2025-01-21 15:55 UTC, rwharrisjr commented on framework/components/AStepperCard/AStepperCard.scss
> +    &--col {
Yep, that'll work. 

Just as a note, I did get carried away with that pattern in early days of the Ribbon code, and wound up with `component__b__c__d__e` sorts of classnames. For things with more than 2 nesting levels I started moving the scss definition a bit higher to end up with just one level of `&__`

2025-01-21 15:55 UTC, rwharrisjr approved these changes

2025-01-21 16:20 UTC, merged